remote_theme: h01000110/windows-95
permalink: /:year:month:day/:title
url: #Your url here
baseurl: /project

# variables
name: Tomato-dev
description: Your description here
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true
